function save_fitdata( handles, pathname, filename )
% exports fit data to pahtname/filename Excel file, sheet 'Fit'

    header = { char(handles.header(handles.col_t)), ...
                'mu (1 / time unit)', ...
                'mu lower (1 / time unit)', ...
                'mu upper (1 / time unit)', ...
                'dtime (time unit)', ...
                'dtime_lower (time unit)', ...
                'dtime_upper (time unit)' };        
    data = [    handles.t_fit, ...
                handles.mu, ...
                handles.mu_lower, ...
                handles.mu_upper, ...
                log(2)./handles.mu, ...
                log(2)./handles.mu_lower, ...
                log(2)./handles.mu_upper ];
    xlswrite([pathname,filename], header, 'Fit', 'A1');
    xlswrite([pathname,filename], data, 'Fit', 'A2');
