function save_runparam( handles, pathname, filename )
% exports running parameters to pathname/filename Excel file, sheet 'Parameters'

    varnames = {'rising_time'; ...
                'rising_time_auto';...
                'width';...
                'width_auto';...
                'midline';...
                'midline_auto';...
                'period';...
                'period_auto';...
                'time_window'; ...
                'time_window_unit'; ...
                'noise_limit';...
                'noise_limit_unit';...
                'min_length';...
                'min_length_unit';...
                'exp_mu_change_percent';...
                'model';...
                'conf_level';...
                'iter_precision';...
                'iter_maxstep';...
                'show_estimate';...
                'show_jumps';...
                'show_smoothregions';...
                'show_fit';...
                'show_confint';...
                'mu_or_dtime';...
                };
    varvalues = [
                handles.risingtime;
                get(handles.checkbox_risingtime,'value');
                handles.width;
                get(handles.checkbox_width,'value');
                handles.midline;
                get(handles.checkbox_midline,'value');
                handles.period;
                get(handles.checkbox_period,'value');
                handles.twindow_numeric;
                get(handles.popupmenu_twindow,'value');
                handles.nwindow_numeric;
                get(handles.popupmenu_nwindow,'value');
                handles.minlength_numeric;
                get(handles.popupmenu_minlength,'value');
                handles.chi*100;
                get(handles.popupmenu_model,'value');
                handles.conflevel;            
                handles.eps;
                handles.itermax;
                get(handles.checkbox_show,'value');
                get(handles.checkbox_jumps,'value');
                get(handles.checkbox_smoothregions,'value');
                get(handles.checkbox_showoscfit,'value');
                get(handles.checkbox_confint,'value');
                get(handles.popupmenu_muplot,'value');
        ];
    xlswrite([pathname,filename], varnames, 'Parameters', 'A1');
    xlswrite([pathname,filename], varvalues, 'Parameters', 'B1');
